/********************************************************************************
 * timercounters.c
 *
 * This set of functions initializes the timer counters (0 and 1) on the xx4P chip
 * and implements periodic interrupts to drive data collection on board the 
 * drone.  A 1Hz interrupt on TC1 is for data collection.  A 100Hz interrupt
 * om TC0 is used for timing purposes on the FATFS when writing to the SD
 * card.  This latter interrupt is not needed in production.
 *
 * Created: 8/14/2017 2:04:46 PM
 * Author: Craig R
 *******************************************************************************/ 

/********************************************************************************
						Includes
********************************************************************************/
#include "canary_common.h"
#include "timercounters.h"
#include <avr/interrupt.h>
#include <avr/io.h>
//#include "integer.h"

/********************************************************************************
						Global Variables
********************************************************************************/

/********************************************************************************
*********************************************************************************
						Functions
*********************************************************************************
********************************************************************************/
void initialize_timer_counter_0(void) 
{
	/* This routine is designed to set up a 100Hz interrupt on the 328PA
	F_CPU is expected to be defined before this routine is called.
	This is in support of the FAT file system library
	@ 20MHz, the prescaler needs to be set to 1024, so CS1[2:0]=0b101.
	The waveform gen mode is 2(CTC, TOP count in OCR0A), so WGM[2:0]=0b010
	Not using any of the other compare features, so all other CR bits are 0
	Finally, we have to enable the interrupt vector on compare register A
	TCCR0A = 0; Control Register A is reset to 0x00 on startup. */
	// Set the WGM mode control register A
	TCCR0A = (1<<WGM01);
	// Set the prescaler select in control register B
	TCCR0B = ((1<<CS12) | (1<<CS10));
	// Now we need to enter our TOP value in OCR0A
	OCR0A = 194;
	// Now enable the interrupt on the compare register A
	TIMSK0 = (1<<OCIE0A);
	// Timer counter 0 set up.  100Hz interrupts will start when sei() is called
}

void initialize_timer_counter_1(void) 
{
	/* This routine is designed to set up a 1Hz interrupt on the 328PA
	F_CPU is expected to be defined before this routine is called.
	@ 20MHz, the prescaler needs to be set to 1024, so CS1[2:0]=0b101.
	The waveform gen mode is 4 (CTC, TOP count in OCR1A), so WGM[3:0]=0b0010
	Not using any of the other compare features, so all other CR bits are 0
	Finally, we have to enable the interrupt vector on compare register A
	TCCR1A = 0; Control Register A is reset to 0x00 on startup. */
	//  
	// Set the WGM mode and prescaler select in control register B
	TCCR1B = ((1<<WGM12) | (1<<CS12) | (1<<CS10));
	// TCCR1C = 0; Control Register C is reset to 0x00 on startup.
	// Now we need to enter out TOP value in OCR1A
	OCR1A = 19530;
	// Now enable the interrupt on the compare register A
	TIMSK1 = (1<<OCIE1A);
	// Timer counter 1 set up.  1Hz interrupts will start when sei() is called
}


/********************************************************************************
*********************************************************************************
						Interrupt Service Routines
*********************************************************************************
********************************************************************************/


// 100Hz timer interrupt generated by OC0A and used by the FATFS code.
EMPTY_INTERRUPT(TIMER0_COMPA_vect);
/*
ISR(TIMER0_COMPA_vect)
{
	Timer++;			// Performance counter for this module 
	disk_timerproc();	//Drive timer procedure of low level disk I/O module 
}
*/


ISR(TIMER1_COMPA_vect)
{
	ToggleBit(PORTB, PORTB1); //for now, just toggle the green status LED
	ItsTime = 1;
}
